version: '3.9'

services:
  postgres:
    image: 'postgres:10-alpine'
    env_file:
      - '.env'
    volumes:
      - 'postgres:/var/lib/postgresql/data'
    ports:
      - '5432:5432'

  website:
    build: .
    command: >
        gunicorn -b 0.0.0.0:8000
        --access-logfile -
        --log-level=debug
        --reload
        "blogexample.app:create_app()"
    env_file:
      - '.env'
    volumes:
      - '.:/app'
    ports:
      - '8000:8000'

volumes:
  postgres:

