from alembic import op
import sqlalchemy as sa

import lib.util_datetime# import tzware_datetime
import lib.util_sqlalchemy# import AwareDateTime


"""create add URL field in Posts model

Revision ID: 29d9055c6a28
Revises: 5deb590e2e6e
Create Date: 2019-07-10 10:06:42.299980

"""



# revision identifiers, used by Alembic.
revision = '29d9055c6a28'
down_revision = '5deb590e2e6e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('url', sa.String(length=128), nullable=False))
    op.create_unique_constraint(None, 'posts', ['url'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'posts', type_='unique')
    op.drop_column('posts', 'url')
    # ### end Alembic commands ###
