from alembic import op
import sqlalchemy as sa

import lib.util_datetime# import tzware_datetime
import lib.util_sqlalchemy# import AwareDateTime


"""added cascade constraints in posts_tags_table for orphan and duplicate control

Revision ID: 5430b6f4296f
Revises: 3a302fcd8d0b
Create Date: 2019-07-12 05:30:15.148295

"""



# revision identifiers, used by Alembic.
revision = '5430b6f4296f'
down_revision = '3a302fcd8d0b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('post_tags_tag_id_fkey', 'post_tags', type_='foreignkey')
    op.drop_constraint('post_tags_post_id_fkey', 'post_tags', type_='foreignkey')
    op.create_foreign_key(None, 'post_tags', 'tags', ['tag_id'], ['id'], ondelete='cascade')
    op.create_foreign_key(None, 'post_tags', 'posts', ['post_id'], ['id'], ondelete='cascade')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'post_tags', type_='foreignkey')
    op.drop_constraint(None, 'post_tags', type_='foreignkey')
    op.create_foreign_key('post_tags_post_id_fkey', 'post_tags', 'posts', ['post_id'], ['id'])
    op.create_foreign_key('post_tags_tag_id_fkey', 'post_tags', 'tags', ['tag_id'], ['id'])
    # ### end Alembic commands ###
