from alembic import op
import sqlalchemy as sa

import lib.util_datetime# import tzware_datetime
import lib.util_sqlalchemy# import AwareDateTime


"""create Posts table

Revision ID: 5deb590e2e6e
Revises: 
Create Date: 2019-07-10 07:44:24.195984

"""



# revision identifiers, used by Alembic.
revision = '5deb590e2e6e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('posts',
    sa.Column('created_on', lib.util_sqlalchemy.AwareDateTime(), nullable=True),
    sa.Column('updated_on', lib.util_sqlalchemy.AwareDateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=128), nullable=False),
    sa.Column('body', sa.String(), nullable=False),
    sa.Column('visible', sa.Boolean(), server_default='1', nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_posts_visible'), 'posts', ['visible'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_posts_visible'), table_name='posts')
    op.drop_table('posts')
    # ### end Alembic commands ###
