from alembic import op
import sqlalchemy as sa

import lib.util_datetime# import tzware_datetime
import lib.util_sqlalchemy# import AwareDateTime


"""empty message

Revision ID: a6db2c3a9b0c
Revises: 5430b6f4296f
Create Date: 2020-02-10 17:00:07.205728

"""



# revision identifiers, used by Alembic.
revision = 'a6db2c3a9b0c'
down_revision = '5430b6f4296f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('name', sa.String(length=128)))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'name')
    # ### end Alembic commands ###
